Module 3, class 3 Assignment

In [ ]:
import pandas as pd #uploading pandas library
url = 'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv'
df = pd.read_csv(url)#opening the file

In [ ]:
obj_cols = df.select_dtypes(include='object').columns.tolist() # it is categorical encoding, select_dtypes(include='object' , 'int') this selects only columns that you want to work with, .columngives the names of columns .tolist makes the indexing python list
print('Total object columns:', len(obj_cols)) #it gives the number of selected columns 'object'columns basically
print(obj_cols) #it shows all the columns we selected

Total object columns: 18
['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges', 'Churn']

In [ ]:
df['gender'].value_counts() #this shows the unique values of gender column, value_counts() is for this service

gender
Male      3555
Female    3488
Name: count, dtype: int64

In [17]:
dummies = pd.get_dummies(df['InternetService'], prefix='Internet') #it is one=hot encoding, dummies refers to the one-hot encoding, this code selects the column InternetService, makes one hot encoding, prefix show the new columnsare from that internet column
print('Shape:', dummies.shape) #shows the number of rows and columns of Internet Service column,(after encoding)
print(dummies) #this shows all the results of one=hot encoding

Shape: (7043, 3)
      Internet_DSL  Internet_Fiber optic  Internet_No
0             True                 False        False
1             True                 False        False
2             True                 False        False
3             True                 False        False
4            False                  True        False
...            ...                   ...          ...
7038          True                 False        False
7039         False                  True        False
7040          True                 False        False
7041         False                  True        False
7042         False                  True        False

[7043 rows x 3 columns]

In [ ]:
dummies2 = pd.get_dummies(df['InternetService'], prefix='Internet', drop_first=True) #same thing happening like the previous cell, but in that one, we are removing the first column of new column we created by encoding
print('With drop_first:', dummies2.shape) #shows the number of rows and columns
dummies2.head() #shows the first 5rows of data

With drop_first: (7043, 2)

   Internet_Fiber optic  Internet_No
0                 False        False
1                 False        False
2                 False        False
3                 False        False
4                  True        False

In [18]:
from sklearn.preprocessing import OneHotEncoder
# Import OneHotEncoder to convert categorical values into binary columns.

ohe = OneHotEncoder(sparse_output=False)
# Create the encoder and return the result as a regular NumPy array.

encoded = ohe.fit_transform(df[['TechSupport']])
# Learn the unique categories and convert the column into one-hot encoded values.

encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(['TechSupport'])
)
# Convert the encoded array into a DataFrame with descriptive column names.

encoded_df.head()
# Display the first five rows of the encoded DataFrame.

   TechSupport_No  TechSupport_No internet service  TechSupport_Yes
0             1.0                              0.0              0.0
1             1.0                              0.0              0.0
2             1.0                              0.0              0.0
3             0.0                              0.0              1.0
4             1.0                              0.0              0.0

In [21]:
multi = pd.get_dummies(df[['gender', 'InternetService', 'TechSupport', 'Contract']], drop_first=True) #now, we are doing one =hot encoding with multiple columns, and dropping the first column of all thosecolumns
print('Shape:', multi.shape) #shows number of columns and rows of data after encoding
multi.head() #showing the first 5 rows

Shape: (7043, 7)

,gender_Male,InternetService_Fiber optic,InternetService_No,TechSupport_No internet service,TechSupport_Yes,Contract_One year,Contract_Two year
0,False,False,False,False,False,False,False
1,True,False,False,False,False,True,False
2,True,False,False,False,False,False,False
3,True,False,False,False,True,True,False
4,False,True,False,False,False,False,False